# Homework7. Dictionaries

### Exercise 1

You are given the following two lists: [‘one’, ‘two’, ‘three’, ‘four’, ‘five’] , [1, 2, 3, 4, 5].  
Create a dictionary called __list_to_dict__ with the first list as keys and the second list as values using python code. Hardcoding the values for the dict does not count!

In [ ]:
#INSERT CODE HERE

In [ ]:
#TESTS FOR EXERCISE 1
assert list_to_dict == {'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

### Exercise 2

You are given the following dictionary called __my_dict__:     
 {  
    "_id": "65af550b3d4b96133180c336",  
    "index": 3,  
    "guid": "d04c4a75-9158-44b2-a87d-1bedfed4f0c6",  
    "isActive": false,  
    "balance": "$1,844.68",  
    "picture": "http://placehold.it/32x32",  
    "age": 40,  
    "eyeColor": "green",  
    "name": "Mandy Horn",  
    "gender": "female",  
    "company": "ZENOLUX",  
    "email": "mandyhorn@zenolux.com",  
    "phone": "+1 (848) 547-2173",  
    "address": "309 Stone Avenue, Brutus, Utah, 2678",  
 }  
a. Extract the values for name and phone and store them in the variable __name__ and __phone__  
b. Get all the keys and store them in a tuple called __my_keys__  
c. Get all the values and store them in a tuple called __my_values__  
d. Search in the dictonary for the key __eyeColor__, if it exists remove it from the dictionary    
e. Write a function which receives a dictionary, and prints each key:value pair on a single line until all lines have been printed

In [ ]:
#INSERT CODE HERE

In [ ]:
#TESTS FOR EXERCISE 2
#a.
assert phone == "+1 (848) 547-2173"
assert name == "Mandy Horn"
#b.
assert my_keys == ('_id', 'index', 'guid', 'isActive', 'balance', 'picture', 'age', 'eyeColor', 'name', 'gender', 'company', 'email', 'phone', 'address')
#c.
assert my_values == ('65af550b3d4b96133180c336', 3, 'd04c4a75-9158-44b2-a87d-1bedfed4f0c6', False, '$1,844.68', 'http://placehold.it/32x32', 40, 'green', 'Mandy Horn', 'female', 'ZENOLUX', 'mandyhorn@zenolux.com', '+1 (848) 547-2173', '309 Stone Avenue, Brutus, Utah, 2678')
#d.
assert "eyeColor" not in my_dict

### Exercise 3

Write a python function which generates a dictionary called __dict_generator__.   
The function will have only one parameter n, and that n will be the number of keys and values to generate and also their values. The keys should be n and the value should be n * n. {n: n*n}  
For example, if n is 15, the dictionary generated by the function should look like:  
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}

In [ ]:
#INSERT CODE HERE

In [ ]:
#TESTS FOR EXERCISE 4
assert dict_generator(10) == {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
assert dict_generator(15) == {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}
assert dict_generator(50) == {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521, 40: 1600, 41: 1681, 42: 1764, 43: 1849, 44: 1936, 45: 2025, 46: 2116, 47: 2209, 48: 2304, 49: 2401, 50: 2500}

### Exercise 4

Write a python function which has 2 parameters, a dictionary and a threshold value.  
If the values in the dictionary is below the threshold value, remove them from the dictionary and return the list of keys.  

As an additional exercise after finishing this exercise  
The list of keys should have a descending order based on their values(the key which had the biggest value should be the first one in the list.  

Example: dict_arg = {“Alex”: 9, “Benjamin”: 8, “Dan”: 10, “Coleen”: 3, “Eduard”: 10, “Flynn”: 2, “Eric”: 1, “George”: 7, “Helen”: 4}
	    threshold = 5

In [ ]:
#INSERT CODE HERE

No tests for this exercise